### ISSUE TITLE
[Bug]: llama pack StreamlitChat run error

### ISSUE THREAD

**Issue by pjaskulski** [run-llama/llama-hub#656]
### Bug Description

After downloading the StreamlitChat pack and trying to run it, I get an error: 
ValueError: Please run this llama-pack directly with `streamlit run [download_dir]/streamlit_chatbot/base.py`.

The cause of the error is a little difference in the parameter name, in the StreamlitChatPack class, **ran_from_main** occurs twice in the `__init__` function while in the call at the end of the base.py file:
StreamlitChatPack(**run_from_main**=True).run()

### Version

0.9.7

### Steps to Reproduce

1. download llama pack StreamlitChat according to the instructions on https://llamahub.ai/l/llama_packs-streamlit_chatbot (CLI Usage)
2. run the app according to the same instructions

### Relevant Logs/Tracbacks

```shell
2023-11-25 14:44:19.010 Uncaught app exception
Traceback (most recent call last):
  File "/home/piotr/ihpan/gpt-4-turbo/venv/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/piotr/ihpan/llamaindex_test/streamlit_chatbot/base.py", line 136, in <module>
    StreamlitChatPack(run_from_main=True).run()
  File "/home/piotr/ihpan/llamaindex_test/streamlit_chatbot/base.py", line 23, in __init__
    raise ValueError(
ValueError: Please run this llama-pack directly with `streamlit run [download_dir]/streamlit_chatbot/base.py`
```

**Comment by carolinedlu** [comment]
Hey @pjaskulski, thanks for sharing this! Just to confirm, you're running the app with the following command:

`streamlit run ./streamlit_chatbot_pack/base.py`

right?

**Comment by pjaskulski** [comment]
> Hey @pjaskulski, thanks for sharing this! Just to confirm, you're running the app with the following command:
> `streamlit run ./streamlit_chatbot_pack/base.py`

streamlit run ./src/hist_chat.py
