### ISSUE TITLE
[Bug]: ConnectTimeoutError when connecting to Opensearch endpoint using OpensearchVectorClient

### ISSUE THREAD

**Issue by meghs94** [run-llama/llama-hub#685]
### Bug Description

I was following this document https://docs.llamaindex.ai/en/latest/examples/vector_stores/OpensearchDemo.html to create an OpenSearchVectorClient. When trying to instantiate a client using:

```
client = OpensearchVectorClient(
    endpoint, idx, 1536, embedding_field=embedding_field, text_field=text_field
)
```

I run into `ConnectionTimeout: ConnectionTimeout caused by - ConnectTimeout(HTTPSConnectionPool(host='<endpoint>', port=9200): Max retries exceeded with url: /<idx> (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9eb830ba60>, 'Connection to <endpoint>. (connect timeout=10)')))`

Using llama-index version 0.9.9
Opensearch cluster created in an AWS account. (Using the endpoint without https://)

### Version

0.9.9

### Steps to Reproduce

1. Create an Opensearch cluster.
2. Execute the code below
```
from os import getenv
from llama_index import SimpleDirectoryReader
from llama_index.vector_stores import (
    OpensearchVectorStore,
    OpensearchVectorClient,
)
from llama_index import VectorStoreIndex, StorageContext

# http endpoint for your cluster (opensearch required for vector index usage)
endpoint = <endpoint>

# index to demonstrate the VectorStore impl
idx = <idx>

# load some sample data
documents = SimpleDirectoryReader(<data>).load_data()

# OpensearchVectorClient stores text in this field by default
text_field = "content"

# OpensearchVectorClient stores embeddings in this field by default
embedding_field = "embedding"

# OpensearchVectorClient encapsulates logic for a single opensearch index with vector search enabled
client = OpensearchVectorClient(
    endpoint, idx, 1536, embedding_field=embedding_field, text_field=text_field
)
```

### Relevant Logs/Tracbacks

```shell
WARNING:opensearch:GET https://<endpoint>:9200/<idx> [status:N/A request:40.043s]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/conda/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/conda/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f9eb81590c0>, 'Connection to <endpoint> timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    body=request.body,
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/conda/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<endpoint>', port=9200): Max retries exceeded with url: /<idx>(Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9eb81590c0>, 'Connection to <endpoint> timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/opensearchpy/connection/http_requests.py", line 190, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
  File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='<endpoint>', port=9200): Max retries exceeded with url: /<idx> (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9eb81590c0>, 'Connection to <endpoint> timed out. (connect timeout=20)'))
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
File /opt/conda/lib/python3.10/site-packages/urllib3/connection.py:174, in HTTPConnection._new_conn(self)
    173 try:
--> 174     conn = connection.create_connection(
    175         (self._dns_host, self.port), self.timeout, **extra_kw
    176     )
    178 except SocketTimeout:

File /opt/conda/lib/python3.10/site-packages/urllib3/util/connection.py:95, in create_connection(address, timeout, source_address, socket_options)
     94 if err is not None:
---> 95     raise err
     97 raise socket.error("getaddrinfo returns an empty list")

File /opt/conda/lib/python3.10/site-packages/urllib3/util/connection.py:85, in create_connection(address, timeout, source_address, socket_options)
     84     sock.bind(source_address)
---> 85 sock.connect(sa)
     86 return sock

TimeoutError: timed out

During handling of the above exception, another exception occurred:

ConnectTimeoutError                       Traceback (most recent call last)
File /opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:703, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    702 # Make the request on the httplib connection object.
--> 703 httplib_response = self._make_request(
    704     conn,
    705     method,
    706     url,
    707     timeout=timeout_obj,
    708     body=body,
    709     headers=headers,
    710     chunked=chunked,
    711 )
    713 # If we're going to release the connection in ``finally:``, then
    714 # the response doesn't need to know about the connection. Otherwise
    715 # it will also try to release it and we'll have a double-release
    716 # mess.

File /opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:386, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    385 try:
--> 386     self._validate_conn(conn)
    387 except (SocketTimeout, BaseSSLError) as e:
    388     # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.

File /opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:1042, in HTTPSConnectionPool._validate_conn(self, conn)
   1041 if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1042     conn.connect()
   1044 if not conn.is_verified:

File /opt/conda/lib/python3.10/site-packages/urllib3/connection.py:358, in HTTPSConnection.connect(self)
    356 def connect(self):
    357     # Add certificate verification
--> 358     self.sock = conn = self._new_conn()
    359     hostname = self.host

File /opt/conda/lib/python3.10/site-packages/urllib3/connection.py:179, in HTTPConnection._new_conn(self)
    178 except SocketTimeout:
--> 179     raise ConnectTimeoutError(
    180         self,
    181         "Connection to %s timed out. (connect timeout=%s)"
    182         % (self.host, self.timeout),
    183     )
    185 except SocketError as e:

ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f9eb81590c0>, 'Connection to <endpoint> timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
File /opt/conda/lib/python3.10/site-packages/requests/adapters.py:489, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    488 if not chunked:
--> 489     resp = conn.urlopen(
    490         method=request.method,
    491         url=url,
    492         body=request.body,
    493         headers=request.headers,
    494         redirect=False,
    495         assert_same_host=False,
    496         preload_content=False,
    497         decode_content=False,
    498         retries=self.max_retries,
    499         timeout=timeout,
    500     )
    502 # Send the request.
    503 else:

File /opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:787, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    785     e = ProtocolError("Connection aborted.", e)
--> 787 retries = retries.increment(
    788     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    789 )
    790 retries.sleep()

File /opt/conda/lib/python3.10/site-packages/urllib3/util/retry.py:592, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    591 if new_retry.is_exhausted():
--> 592     raise MaxRetryError(_pool, url, error or ResponseError(cause))
    594 log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)

MaxRetryError: HTTPSConnectionPool(host='<endpoint>', port=9200): Max retries exceeded with url: /<idx> (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9eb81590c0>, 'Connection to <endpoint> timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

ConnectTimeout                            Traceback (most recent call last)
File /opt/conda/lib/python3.10/site-packages/opensearchpy/connection/http_requests.py:190, in RequestsHttpConnection.perform_request(self, method, url, params, body, timeout, allow_redirects, ignore, headers)
    189 try:
--> 190     response = self.session.send(prepared_request, **send_kwargs)
    191     duration = time.time() - start

File /opt/conda/lib/python3.10/site-packages/requests/sessions.py:701, in Session.send(self, request, **kwargs)
    700 # Send the request
--> 701 r = adapter.send(request, **kwargs)
    703 # Total elapsed time of the request (approximately)

File /opt/conda/lib/python3.10/site-packages/requests/adapters.py:553, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    552     if not isinstance(e.reason, NewConnectionError):
--> 553         raise ConnectTimeout(e, request=request)
    555 if isinstance(e.reason, ResponseError):

ConnectTimeout: HTTPSConnectionPool(host='<endpoint>', port=9200): Max retries exceeded with url: /<idx>(Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9eb81590c0>, '<endpoint> timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

ConnectionTimeout                         Traceback (most recent call last)
Cell In[248], line 25
     21 embedding_field = "embedding"
     22 # OpensearchVectorClient encapsulates logic for a
     23 # single opensearch index with vector search enabled
     24 # try :
---> 25 client = OpensearchVectorClient(
     26     endpoint, idx, 1024, embedding_field=embedding_field, text_field=text_field, http_auth=awsauth, use_ssl=True,
     27         verify_certs=True,
     28         connection_class=RequestsHttpConnection,
     29     timeout=20
     30 )
     31 # except Exception as e:
     32 #     print("ERROR")
     33 #     import logging
   (...)
     38 # # initialize an index using our sample data and the client we just created
     39 # index = VectorStoreIndex(google_nodes, storage_context=storage_context)

File /opt/conda/lib/python3.10/site-packages/llama_index/vector_stores/opensearch.py:225, in OpensearchVectorClient.__init__(self, endpoint, index, dim, embedding_field, text_field, method, max_chunk_bytes, **kwargs)
    223 not_found_error = _import_not_found_error()
    224 try:
--> 225     self._os_client.indices.get(index=self._index)
    226 except not_found_error:
    227     self._os_client.indices.create(index=self._index, body=idx_conf)

File /opt/conda/lib/python3.10/site-packages/opensearchpy/client/utils.py:179, in query_params.<locals>._wrapper.<locals>._wrapped(*args, **kwargs)
    176         if v is not None:
    177             params[p] = _escape(v)
--> 179 return func(*args, params=params, headers=headers, **kwargs)

File /opt/conda/lib/python3.10/site-packages/opensearchpy/client/indices.py:197, in IndicesClient.get(self, index, params, headers)
    194 if index in SKIP_IN_PATH:
    195     raise ValueError("Empty value passed for a required argument 'index'.")
--> 197 return self.transport.perform_request(
    198     "GET", _make_path(index), params=params, headers=headers
    199 )

File /opt/conda/lib/python3.10/site-packages/opensearchpy/transport.py:409, in Transport.perform_request(self, method, url, headers, params, body)
    407             raise e
    408     else:
--> 409         raise e
    411 else:
    412     # connection didn't fail, confirm it's live status
    413     self.connection_pool.mark_live(connection)

File /opt/conda/lib/python3.10/site-packages/opensearchpy/transport.py:370, in Transport.perform_request(self, method, url, headers, params, body)
    367 connection = self.get_connection()
    369 try:
--> 370     status, headers_response, data = connection.perform_request(
    371         method,
    372         url,
    373         params,
    374         body,
    375         headers=headers,
    376         ignore=ignore,
    377         timeout=timeout,
    378     )
    380     # Lowercase all the header names for consistency in accessing them.
    381     headers_response = {
    382         header.lower(): value for header, value in headers_response.items()
    383     }

File /opt/conda/lib/python3.10/site-packages/opensearchpy/connection/http_requests.py:207, in RequestsHttpConnection.perform_request(self, method, url, params, body, timeout, allow_redirects, ignore, headers)
    205         raise SSLError("N/A", str(e), e)
    206     if isinstance(e, requests.Timeout):
--> 207         raise ConnectionTimeout("TIMEOUT", str(e), e)
    208     raise ConnectionError("N/A", str(e), e)
    210 # raise warnings if any from the 'Warnings' header.

ConnectionTimeout: ConnectionTimeout caused by - ConnectTimeout(HTTPSConnectionPool(host='<endpoint>', port=9200): Max retries exceeded with url: /<idx> (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9eb81590c0>, 'Connection to <endpoint> timed out. (connect timeout=20)')))
```

**Comment by meghs94** [comment]
I was able to resole it by adding port .

client = OpensearchVectorClient(endpoint, idx, 1024, embedding_field=embedding_field, text_field=text_field, http_auth=awsauth, use_ssl=True, verify_certs=True, connection_class=RequestsHttpConnection, timeout=10, port=port
)
