### ISSUE TITLE
[Bug]: Install via CLI fails

### ISSUE THREAD

**Issue by pytony17** [run-llama/llama-hub#706]
### Bug Description

I tried to install the streamlit llama-index chatbot per the instructions. Pretty straightforward. I installed the llama-index package and then ran the cli installer. But the installer failed. Details below.

### Version

Version: 0.9.10

### Steps to Reproduce

pip install llama-index
llamaindex-cli download-llamapack StreamlitChatPack --download-dir ./streamlit_chatbot_pack

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\Documents\PythonProjects\LlamaPacksChatbot\.venv\Scripts\llamaindex-cli.exe\__main__.py", line 7, in <module>       
  File "C:\Users\User\Documents\PythonProjects\LlamaPacksChatbot\.venv\Lib\site-packages\llama_index\command_line\command_line.py", line 122, in main
    args.func(args)
  File "C:\Users\User\Documents\PythonProjects\LlamaPacksChatbot\.venv\Lib\site-packages\llama_index\command_line\command_line.py", line 80, in <lambda>
    func=lambda args: handle_download_llama_pack(**vars(args))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\PythonProjects\LlamaPacksChatbot\.venv\Lib\site-packages\llama_index\command_line\command_line.py", line 20, in handle_download_llama_pack
    download_llama_pack(
  File "C:\Users\User\Documents\PythonProjects\LlamaPacksChatbot\.venv\Lib\site-packages\llama_index\llama_pack\download.py", line 24, in download_llama_pack
    pack_cls = download_llama_module(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\PythonProjects\LlamaPacksChatbot\.venv\Lib\site-packages\llama_index\download\download_utils.py", line 305, in download_llama_module
    download_module_and_reqs(
  File "C:\Users\User\Documents\PythonProjects\LlamaPacksChatbot\.venv\Lib\site-packages\llama_index\download\download_utils.py", line 201, in download_module_and_reqs
    f.write(basepy_raw_content)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f999' in position 1166: character maps to <undefined>
```

**Comment by carolinedlu** [comment]
Hi @pytony17, thanks for sharing this! Are you using the most recent version of LlamaIndex / the LlamaIndex CLI?

**Comment by pytony17** [comment]
hi @carolinedlu  I created a fresh virtual environment in VScode and ran the pip install llama-index command. I also ran pip install --upgrade llama-index. So I believe I have the latest version. Still get the same error when I run the llamaindex-cli command. Let me know if I can provide any additional info. Thanks!

**Comment by tonykipkemboi** [comment]
Hi @pytony17, have you tried running it without the virtual environment?

**Comment by pytony17** [comment]
@tonykipkemboi I tried installing without a virtual environment but it gets stuck because it cannot install multidict package. something to do with Microsoft C++ Build Tools. I tried installing C++ several different ways, but the install for multidict still won't go.

**Comment by vicalbiter** [comment]
Hi @pytony17, I had the same problem. If you're on Windows (which appears to be the case), where the default character encoding is not "UTF-8", this solution might work for you too:

- Go to <path_to_llama_index_directory>/download/module.py. In _your_ case, I see that your specific <path_to_llama_index_directory> is **C:\Users\User\Documents\PythonProjects\LlamaPacksChatbot\.venv\Lib\site-packages\llama_index**.
- Look for the function called **download_module_and_reqs**.

Replace this:
```
with open(f"{module_path}/{base_file_name}", "w") as f:
    f.write(basepy_raw_content)
```

For this:
```
with open(f"{module_path}/{base_file_name}", "w", encoding="utf-8") as f:
    f.write(basepy_raw_content)
```

I think the problem is essentially that Windows' default encoding (cp1252) for your python env doesn't support emojis. The character causing the problem, '\U0001f999', is an emoji.

**Comment by pytony17** [comment]
Thank you @vicalbiter ! Your recommended code change to add the utf-8 encoding parameter fixed the installation issue. Much appreciated.
